### ISSUE TITLE
API para manter fichas de avaliação de uma aluno em uma turma e um bimestre.

### ISSUE THREAD

**Issue by keviocastro** [keviocastro/schools#4]
Será criado o end-point api/student-progress-sheet.

# Grupo Estudantes

### Sub-tasks:
- [x] Listar itens de avaliações. @weuder
- [x] Criar item de avaliação.  @keviocastro 

* Condições de sucesso:
    * [x] Só pode ser registrado o resultado de um aluno para um item de avaliação se o aluno estiver
matriculado na turma.
    * [x]  O aluno pode ter somente um resposta de um item de avaliação, em uma fase do ano, para uma turma.
Isso significa que um requisição com a combinação de parametros progress_sheet_item_id, school_calendar_phase_id,
school_class_id e student_id, já existirem, um novo registro não será criado e sim atualizado.
No caso de atualização do registro o código de resposta é 200 e em casos de criação o código de resposta é 201.

### Sub-tasks:
- [x] Detalhes do item de avaliação. @weuder
- [x] Alterar item de avaliação. @weuder
- [x] Deletar item de avaliação. @weuder
