### ISSUE TITLE
API Para manter fichas de avaliação descritivas

### ISSUE THREAD

**Issue by keviocastro** [keviocastro/schools#7]
Para alunos do ensino infantil e alguns anos do fundamental 1, as avaliações devem ser por fichas descritivas, conforme definido aqui: https://zpl.io/Z18xWs6.

Deve ser criado recurso na API para manter esses modelos de fichas de avaliação.

Serão criados os end-points:

api/progress-sheets
api/progress-sheets/{progress_sheet_id}/items

Onde progress-sheets é a definição da ficha de avaliação;
progress-sheet-items são os itens do modelo da ficha.

A estrutura da documentação da API deve ser reorganizada da seguinte forma:

# Grupo Avaliações

## Coleção de fichas avaliativas
Resource URI:  api/progress-sheets/{progress_sheet_id}
 
### Sub-Tasks: 
- [x] Listar fichas. @weuder 
- [x] Criar ficha. @weuder 

## Detalhes da ficha avaliativa
Resource URI:  api/progress-sheets/{progress_sheet_id}

### Sub-Tasks: 
- [x] Detalhes da ficha avaliativa.  @weuder 
- [x] Alterar ficha. @weuder 
- [x] Excluir ficha. @weuder 

### Coleção de itens da ficha avaliativa 
Resource URI:  api/progress-sheets/{progress_sheet_id}/items

### Sub-Tasks: 
- [x] Listar itens da ficha. @keviocastro
- [x] Criar item da ficha. @keviocastro 

## Detalhes do item da ficha avaliativa
Resource URI:  api/progress-sheets/{progress_sheet_id}/items/{item_id}

# Sub-tasks para ambiente de desenvolvimento

- [x] Atualizar seeder SchoolCalendar2017 para criar turmas com ficha de avaliação como formato de avaliação
- [x] Atualizar seeder  SchoolCalendar2017 para definir faltas para os alunos de turmas com avaliação de turmas interdisciplinares.
